# Generated by Django 5.2.3 on 2025-06-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_input', models.TextField()),
                ('data_output', models.TextField()),
            ],
        ),
    ]
